version: '3.4'
services:
  landing:
    build: landing
    ports:
    - "8080:80"
  sql_injection:
    build: sql_injection
    ports:
    - "81:80"
    secrets:
    - source: sql_injection_id
      target: task_id
  obvious_password:
    build: obvious_password
    ports:
    - "82:80"
    secrets:
    - source: obvious_password_id
      target: task_id
  api:
    build: api
    ports:
    - "69:80" # Remove this port in production
    expose:
    - "80"
    secrets:
    - sql_injection_id
    - obvious_password_id
    - task_3
    - task_4
    - task_5
    - tasks
secrets:
  tasks:
    file: tasks.json
  sql_injection_id:
    file: sql_injection/secret_id
  obvious_password_id:
    file: obvious_password/secret_id
  task_3:
    file: task3_id
  task_4:
    file: task4_id
  task_5:
    file: task5_id